source/objects/WorkforceTeamNotification__c.object
<CustomObject>
    <fields>
        <fullName>APINotificationStatus__c</fullName>
        <label>API Notification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AgentId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Id</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WorkforcePlanningTeamNotification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Id</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>WorkforcePlanningTeamNotification</relationshipLabel>
        <relationshipName>WorkforcePlanningTeamNotification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Workforce PlanningTeam Notification</label>
    <nameField>
        <displayFormat>WFM-{0000000}</displayFormat>
        <label>WorkforceTeamNotification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WorkforcePlanningTeamNotification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/classes/WFMTeamNotificationBatchService.cls
public with sharing class WFMTeamNotificationBatchService implements Database.Batchable<sObject>,Database.AllowsCallouts {
    
    //variables and constants declaration
    private static final String STATUS='Pending';
    private String query;

    //Constructor -Build the SQL queryfor the closed cases with status 'Pending' from WorkforcePlanningTeamNotification table
    public WFMTeamNotificationBatchService(){
        query='select Id,CaseId__c,AgentId__c,APINotificationStatus__c,ErrorMessage__c from WorkforceTeamNotification__c Where APINotificationStatus__c =:STATUS';
    }

    //Add additional predicate with 5 min delay from thier created date
    public Database.QueryLocator start(Database.BatchableContext BC) {
        Datetime currTimeMinusFive = Datetime.now().addMinutes(-5);         
        if( !Test.isRunningTest() )  query += ' AND CreatedDate <= :currTimeMinusFive ';
        return Database.getQueryLocator(query);
    }

    //Invoke service for each closed case, Execute method is called once for each case from the above query(i.e scope has 1 record) allowing more time to complete the API successfully.  
    public void execute(Database.BatchableContext BC, List<WorkforceTeamNotification__c> scope) {

        Savepoint sp = Database.setSavepoint();
        try{
            for(WorkforceTeamNotification__c WFMNoticationInpRec:scope){
                WFMTeamNotificationServiceHelper.initiateServiceCall(WFMNoticationInpRec);
            } 
        }
        catch(Exception ex) { 
            Database.rollback(sp);
            for(WorkforceTeamNotification__c wftn : scope) {
                wftn.ErrorMessage__c = ex.getMessage() + ' ' + ex.getStackTraceString();
                wftn.APINotificationStatus__c = WFM_Constants.STATUS_ERROR;
            }
            update scope;
        }       
    }
    public void finish(Database.BatchableContext BC) {

    }
}